### ISSUE TITLE
Main menu text color problem  - monterail theme

### ISSUE THREAD

**Issue by lupa18** [spymastermatt/thunderbird-monterail#57] opened 2017-05-30 17:57 UTC
It seems to be the same color problem in search box and main menu in monterail theme. Look at the screenshot:

![seleccion_404](https://cloud.githubusercontent.com/assets/463429/26597321/a70358b2-453f-11e7-84e5-d171ee0f841c.png)

**Comment by spymastermatt** [comment] 2017-05-31 07:37
Hi @lupa. Was the menu issue not fixed by the search box fix I pushed? Can you try the latest version and let me know. Thanks for reporting these :)

**Comment by Somnambulated** [comment] 2017-05-31 09:23
Confirmed fixed on mine after installing the update.

**Comment by jacklenox** [comment] 2017-06-06 02:54
Yep, I use the "dark" theme and this is still happening. Beautiful theme all the same though!

**Comment by lupa18** [comment] 2017-06-08 19:10
In dark theme works well. Only having problems when create new message, but I'll open new issue. 

In monteraill still happening (I have last github version). Attached image: 

![seleccion_417](https://user-images.githubusercontent.com/463429/26946193-84787f38-4c5c-11e7-8288-8934afa1e5ab.png)

**Comment by franklinovitch** [comment] 2017-06-15 10:29
Hi, PR #62 should solve this issue for Monterail theme!

<img width="591" alt="capture d ecran 2017-06-15 a 12 26 47" src="https://user-images.githubusercontent.com/6093315/27177316-38d96dac-51c6-11e7-9d85-e8f2ab4ed33f.png">

Have a good day :)

**Comment by jacklenox** [comment] 2017-06-16 06:43
This doesn't seem to work for me, though I'm not sure if that's just because I need to bust the cache. Anyone know how to do this?

**Comment by PrzemekSkw** [comment] 2017-06-22 19:03
@franklinovitch Hi, what is PR #62 ?

**Comment by jacklenox** [comment] 2017-06-29 18:48
Hmm, this doesn't seem to have fixed it for me. :confused:

**Comment by spymastermatt** [comment] 2017-06-29 19:17
Hmm @jacklenox have you edited any of the files (including the variables)?
Could you post any changes you have made. Thanks

**Comment by spymastermatt** [comment] 2017-06-29 19:17
Also, what OS are you using?

**Comment by jdreesen** [comment] 2017-06-29 19:26
Doesn't work for me either. Only change I made is switching from system to monterail theme. 
This is how it looks for me on latest master: 
![tb-menu](https://user-images.githubusercontent.com/424602/27706323-796892f2-5d11-11e7-96d6-e01ee06e2f4c.png)

**Comment by spymastermatt** [comment] 2017-06-29 19:48
Well I'm an idiot!!
I fixed the issue and then tidied up the code and somehow managed to remove the fix in the process :s
It should now actually be fixed

**Closed** 2017-06-29 19:47 UTC

**Comment by jdreesen** [comment] 2017-06-29 20:51
Now it's perfect, thx :)

Screenshot from latest master with monterail theme:
![main-menu](https://user-images.githubusercontent.com/424602/27709691-5470fd8e-5d1d-11e7-96c2-6933d5333193.png)

**Comment by jacklenox** [comment] 2017-06-29 20:53
Yep perfect, me too! Thanks @spymastermatt, and I understand the feeling – not an idiot at all! :grinning:

This theme is so awesome.

**Comment by PrzemekSkw** [comment] 2017-06-30 06:22
Hi, thanks for fix. Menu is OK but I find white font in New Messege window and Preferences:
![deepinscreenshot20170630081710](https://user-images.githubusercontent.com/25219988/27723405-3339397e-5d6d-11e7-8839-33a250e12a25.png)

**Comment by jacklenox** [comment] 2017-07-11 21:08
Yep, the same thing is happening for me too. ^^

**Comment by jdreesen** [comment] 2017-07-11 22:43
I can confirm that.
