### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by techdev5521** [spymastermatt/thunderbird-monterail#11] opened 2017-04-28 04:09 UTC
The theme does not work on macOS at all. This may be because of Thunderbird using Cocoa instead of GTK+ to draw itself, but I am not totally sure.

**Comment by spymastermatt** [comment] 2017-04-28 06:54
Hi @techdev5521, which variant are you using?

**Comment by cbf305** [comment] 2017-04-28 10:22
Same here.  All variants don't work for the most part. It does apply some styling, but it's no where near what is shown in the screenshots.  All of them applied spacing to the messages pane, icons to the folder pane, and font colors to the folder pane, but all the chrome was still the silvery macOS default and the folder pane was just pure white.

Attached is a screenshot of what the dark variant looks like, although they all pretty much look the same.
![screen shot 2017-04-28 at 6 15 30 am](https://cloud.githubusercontent.com/assets/2612500/25525056/fc01631e-2bda-11e7-8916-ac66ae17f510.png)

**Comment by spymastermatt** [comment] 2017-04-28 13:04
Ah OK this seems to be something that crops up a lot and it's not a bug as such, just me being confusing with my naming.

The light, dark and fulldark variants are for use with system themes that are light/dark/fulldark. They are not dark etc variants in themselves.

I will fix this in a few days, with one userChrome-gtk which should automatically adapt to the current theme, after which I will make the dark and fulldark variants true 'themes' with specified dark colours.

**Comment by sg-s** [comment] 2017-04-28 13:50
see this [link](https://monterail.com/blog/2016/the-power-of-email-clients-why-did-we-redesign-thunderbird?utm_source=Thunderbird&utm_campaign=Dribbble&utm_medium=blogpost%22)

they have a link to something they say works across platforms

**Comment by spymastermatt** [comment] 2017-05-02 20:56
Hey all, sorry for being quiet for the past few days, I have been working on a big update (coming tomorrow hopefully) which fixes almost all open issues (including this one)

**Comment by spymastermatt** [comment] 2017-05-04 19:27
Hi everyone.
This should now have been resolved by a complete rewrite (and refactor).
Please discard the old versions and download the new ones.

Thanks everyone for helping out with bug reports and fixes!!

**Closed by spymastermatt** 2017-05-04 19:27 UTC
